### ISSUE TITLE
ExponentiallyDecayingSample Update throws System.InvalidOperationException

### ISSUE THREAD

**Issue by Yitzchok** [danielcrenna/metrics-net#45]
This is the error

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Min(IEnumerable`1 source)
   at metrics.Stats.ExponentiallyDecayingSample.Update(Int64 value, Int64 timestamp) in d:\Src\metrics-net\src\metrics\Stats\ExponentiallyDecayingSample.cs:line 87
   at metrics.Stats.ExponentiallyDecayingSample.Update(Int64 value) in d:\Src\metrics-net\src\metrics\Stats\ExponentiallyDecayingSample.cs:line 68
   at metrics.Core.HistogramMetric.Update(Int64 value) in d:\Src\metrics-net\src\metrics\Core\HistogramMetric.cs:line 99
   at metrics.Core.TimerMetricBase.Update(Int64 duration) in d:\Src\metrics-net\src\metrics\Core\TimerMetricBase.cs:line 206
   at metrics.Core.TimerMetric.Time[T](Func`1 event) in d:\Src\metrics-net\src\metrics\Core\TimerMetric.cs:line 51
```

**Comment by gbrusella** [comment]
I've been using ExponentiallyDecayingSample with no problems... Can you post a repro sample?

**Comment by sotodel** [comment]
We are having issues with ExponentiallyDecayingSample as well. I don't have a reproducible sample for you. However, our environment is extremely multithreaded. In other words, multiple threads are accessing and updating the same ExponentiallyDecayingSample. Eventually (after 10-15 hours), the _values dictionary becomes empty and the call to _values.Keys.Min() throws an exception, https://github.com/danielcrenna/metrics-net/blob/master/src/metrics/Stats/ExponentiallyDecayingSample.cs#L87. 

At that point, without a Clear(), the corresponding Timer becomes completely unusable. 

We are working in a mono development.

**Comment by sotodel** [comment]
It seems like if you get a collision while inserting into the dictionary, however unlikely, you end up removing an element, but never making up for it. If this keeps happening, you end up with an empty dictionary.

**Comment by sotodel** [comment]
Actually this happens when you're running your app so long that `timestamp - _startTime` returns a value large enough that `Math.Exp(_alpha * t)` returns `Infinity`. That screws up everything else because `priority` also becomes `Infinity` and causes collisions while adding to the `Dictionary` which reduces its size by 1 on every update.

**Comment by danielcrenna** [comment]
Hmm. How could it be re-based without data loss?

**Comment by sotodel** [comment]
I don't know any of the math behind these calculations but it seems like `Exp` grows way too fast.
